### ISSUE TITLE
[BUG]  DATABASE_URL with `?sslmode=<any>` crashes asyncpg engine at startup with ClientConfigurationError

### ISSUE THREAD

**Issue by AllenQU-LR** [ibbybuilds/aegra#404]
**Describe the bug**
Setting DATABASE_URL=postgresql://...?sslmode=<value> crashes the asyncpg engine at startup with ClientConfigurationError: 'sslmode' parameter must be one of: disable, allow, prefer, require, verify-ca, verify-full — even when the value is one of those (e.g. disable,
  require).

  Root cause is in libs/aegra-api/src/aegra_api/settings.py: the _SSLMODE_TO_ASYNCPG map (introduced in PR #390 / commit 804190e) translates libpq sslmode=X to asyncpg ssl=true or ssl=false. asyncpg ≥ 0.28 strict-validates string ssl kwargs via SSLMode.parse(), which only
  accepts libpq sslmode spellings — "true"/"false" raise the (misleadingly worded) error above.

  The error message points at sslmode, so it's not obvious at first that the breakage is in aegra's translation of the user-supplied URL.

**To Reproduce**
  1. Set DATABASE_URL with any sslmode query param:
  export DATABASE_URL='postgresql://user:pass@host:5432/db?sslmode=disable' or allow
  2. Start aegra:
  uv run aegra dev
  3. Startup fails with ClientConfigurationError.

  Minimal repro without booting aegra:
```
  import os, asyncio
  os.environ['DATABASE_URL'] = 'postgresql://user:pass@host:5432/db?sslmode=disable' or allow

  from aegra_api.settings import DatabaseSettings
  from sqlalchemy.ext.asyncio import create_async_engine
  from sqlalchemy import text 

  async def main():
      db = DatabaseSettings(_env_file=None)
      print(db.database_url)  # → postgresql+asyncpg://...?ssl=false
      engine = create_async_engine(db.database_url)
      async with engine.connect() as conn:    # crashes here
          await conn.execute(text("SELECT 1"))

  asyncio.run(main())
```
  
  Confirm asyncpg itself rejects the produced value:
  from asyncpg.connect_utils import SSLMode
```
  SSLMode.parse("false")
  # AttributeError: type object 'SSLMode' has no attribute 'false'
  # → re-raised as ClientConfigurationError in connect_utils.py:680-687
```

**Expected behavior**

Setting ?sslmode=disable (or any valid libpq sslmode) should succeed — this is the standard spelling copied from RDS / Cloud SQL / Azure / Heroku console connection strings, and was explicitly the case PR #390 set out to support.

**Actual behavior**

Show the error like below
```
asyncpg.exceptions._base.ClientConfigurationError: `sslmode` parameter must be one of: disable, allow, prefer, require, verify-ca, verify-full
```
  The aegra-translated URL ends with ?ssl=true or ?ssl=false. SQLAlchemy's asyncpg dialect (sqlalchemy/dialects/postgresql/asyncpg.py:1129, create_connect_args) forwards the raw string verbatim — it does not coerce ssl=<str> to a boolean. asyncpg then calls
  SSLMode.parse("true") / SSLMode.parse("false"), neither of which exists on the SSLMode enum, and raises.

**Environment:**
  - OS: macOS 14 / Linux (reproduces anywhere)
  - Python version: 3.12
  - Aegra version: 0.9.18 (bug present since PR #390, commit 804190e)
  - LangGraph version: any (irrelevant to this code path)

**Configuration:**
- Database: any PostgreSQL reachable via a URL with ?sslmode= — most prominently managed Postgres / Cloud SQL Proxy / RDS / Azure / Heroku.
  - Auth type: any (orthogonal)
  - Deployment: any (local, docker, kubernetes). I hit it on a GCP Cloud SQL Auth Proxy setup where sslmode=disable is required because the proxy terminates TLS at its own layer.

**Logs/Error Messages:**
```
File ".../sqlalchemy/dialects/postgresql/asyncpg.py", line 1129, in create_connect_args
    ...
  File ".../asyncpg/connect_utils.py", line 682, in _parse_connect_dsn_and_args
    sslmode = SSLMode.parse(ssl)
  File ".../asyncpg/connect_utils.py", line 48, in parse
    return getattr(cls, sslmode.replace('-', '_'))
  asyncpg.exceptions._base.ClientConfigurationError: `sslmode` parameter must be one of: disable, allow, prefer, require, verify-ca, verify-full
```

**Additional context**
 - PR #390 correctly identified that asyncpg rejects sslmode= as a kwarg, and correctly renamed the param to ssl=. But it picked "true"/"false" as the value, which doesn't survive asyncpg's string-ssl validation introduced/tightened in 0.28+ (current min in this project is
  asyncpg>=0.30.0). All shipping aegra installs are affected.
  - The existing test (tests/unit/test_settings.py::test_async_url_translates_all_sslmode_values) only asserts URL-string composition — it never instantiates an asyncpg connection or runs SSLMode.parse(), which is why the bug shipped and no CI signal caught it.
  - database_url_sync (used for psycopg / LangGraph checkpointer + store) is unaffected — psycopg speaks libpq natively and accepts sslmode= as-is.
  - Ironic note: omitting sslmode from the URL works around the bug. asyncpg's default with no ssl kwarg is SSLMode.disable (connect_utils.py:815), not libpq's prefer. So users who left the URL alone never hit this; the bug specifically punishes users who explicitly set
  sslmode=.

**Possible Solution**

PR created here: https://github.com/aegra/aegra/pull/405
