### PR TITLE
fix(settings): translate sslmode using libpq spellings asyncpg accepts

### LINKED ISSUE #404: [BUG]  DATABASE_URL with `?sslmode=<any>` crashes asyncpg engine at startup with ClientConfigurationError
**Describe the bug**
Setting DATABASE_URL=postgresql://...?sslmode=<value> crashes the asyncpg engine at startup with ClientConfigurationError: 'sslmode' parameter must be one of: disable, allow, prefer, require, verify-ca, verify-full — even when the value is one of those (e.g. disable,
  require).

  Root cause is in libs/aegra-api/src/aegra_api/settings.py: the _SSLMODE_TO_ASYNCPG map (introduced in PR #390 / commit 804190e) translates libpq sslmode=X to asyncpg ssl=true or ssl=false. asyncpg ≥ 0.28 strict-validates string ssl kwargs via SSLMode.parse(), which only
  accepts libpq sslmode spellings — "true"/"false" raise the (misleadingly worded) error above.

  The error message points at sslmode, so it's not obvious at first that the breakage is in aegra's translation of the user-supplied URL.

**To Reproduce**
  1. Set DATABASE_URL with any sslmode query param:
  export DATABASE_URL='postgresql://user:pass@host:5432/db?sslmode=disable' or allow
  2. Start aegra:
  uv run aegra dev
  3. Startup fails with ClientConfigurationError.

  Minimal repro without booting aegra:
```
  import os, asyncio
  os.environ['DATABASE_URL'] = 'postgresql://user:pass@host:5432/db?sslmode=disable' or allow

  from aegra_api.settings import DatabaseSettings
  from sqlalchemy.ext.asyncio import create_async_engine
  from sqlalchemy import text 

  async def main():
      db = DatabaseSettings(_env_file=None)
      print(db.database_url)  # → postgresql+asyncpg://...?ssl=false
      engine = create_async_engine(db.database_url)
      async with engine.connect() as conn:    # crashes here
          await conn.execute(text("SELECT 1"))

  asyncio.run(main())
```
  
  Confirm asyncpg itself rejects the produced value:
  from asyncpg.connect_utils import SSLMode
```
  SSLMode.parse("false")
  # AttributeError: type object 'SSLMode' has no attribute 'false'
  # → re-raised as ClientConfigurationError in connect_utils.py:680-687
```

**Expected behavior**

Setting ?sslmode=disable (or any valid libpq sslmode) should succeed — this is the standard spelling copied from RDS / Cloud SQL / Azure / Heroku console connection strings, and was explicitly the case PR #390 set out to support.

**Actual behavior**

Show the error like below
```
asyncpg.exceptions._base.ClientConfigurationError: `sslmode` parameter must be one of: disable, allow, prefer, require, verify-ca, verify-full
```
  The aegra-translated URL ends with ?ssl=true or ?ssl=false. SQLAlchemy's asyncpg dialect (sqlalchemy/dialects/postgresql/asyncpg.py:1129, create_connect_args) forwards the raw string verbatim — it does not coerce ssl=<str> to a boolean. asyncpg then calls
  SSLMode.parse("true") / SSLMode.parse("false"), neither of which exists on the SSLMode enum, and raises.

**Environment:**
  - OS: macOS 14 / Linux (reproduces anywhere)
  - Python version: 3.12
  - Aegra version: 0.9.18 (bug present since PR #390, commit 804190e)
  - LangGraph version: any (irrelevant to this code path)

**Configuration:**
- Database: any PostgreSQL reachable via a URL with ?sslmode= — most prominently managed Postgres / Cloud SQL Proxy / RDS / Azure / Heroku.
  - Auth type: any (orthogonal)
  - Deployment: any (local, docker, kubernetes). I hit it on a GCP Cloud SQL Auth Proxy setup where sslmode=disable is required because the proxy terminates TLS at its own layer.

**Logs/Error Messages:**
```
File ".../sqlalchemy/dialects/postgresql/asyncpg.py", line 1129, in create_connect_args
    ...
  File ".../asyncpg/connect_utils.py", line 682, in _parse_connect_dsn_and_args
    sslmode = SSLMode.parse(ssl)
  File ".../asyncpg/connect_utils.py", line 48, in parse
    return getattr(cls, sslmode.replace('-', '_'))
  asyncpg.exceptions._base.ClientConfigurationError: `sslmode` parameter must be one of: disable, allow, prefer, require, verify-ca, verify-full
```

**Additional context**
 - PR #390 correctly identified that asyncpg rejects sslmode= as a kwarg, and correctly renamed the param to ssl=. But it picked "true"/"false" as the value, which doesn't survive asyncpg's string-ssl validation introduced/tightened in 0.28+ (current min in this project is
  asyncpg>=0.30.0). All shipping aegra installs are affected.
  - The existing test (tests/unit/test_settings.py::test_async_url_translates_all_sslmode_values) only asserts URL-string composition — it never instantiates an asyncpg connection or runs SSLMode.parse(), which is why the bug shipped and no CI signal caught it.
  - database_url_sync (used for psycopg / LangGraph checkpointer + store) is unaffected — psycopg speaks libpq natively and accepts sslmode= as-is.
  - Ironic note: omitting sslmode from the URL works around the bug. asyncpg's default with no ssl kwarg is SSLMode.disable (connect_utils.py:815), not libpq's prefer. So users who left the URL alone never hit this; the bug specifically punishes users who explicitly set
  sslmode=.

**Possible Solution**

PR created here: https://github.com/aegra/aegra/pull/405

### PR DESCRIPTION
**Pull request by AllenQU-LR**
## Description

  Fixes a startup crash when `DATABASE_URL` contains any `?sslmode=` query param. The translation introduced in #390 rewrote `sslmode=X` to `ssl=true` / `ssl=false`, but asyncpg ≥ 0.28 strict-validates string `ssl` kwargs via `SSLMode.parse()`, which only accepts libpq sslmode
  spellings (`disable`/`allow`/`prefer`/`require`/`verify-ca`/`verify-full`). `"true"` and `"false"` both raise `ClientConfigurationError`, so every aegra install that uses `?sslmode=` in the URL — the standard shape copied from RDS / Cloud SQL / Azure / Heroku consoles —
  crashes at startup.

  The fix renames `sslmode=X` → `ssl=X` and passes the value through verbatim. asyncpg's string `ssl` kwarg, when given a libpq sslmode value, runs `SSLMode.parse()` and behaves identically to libpq.

  ## Type of Change

  - [x] `fix`: Bug fix

  ## Related Issues

 Closes #404 

  ## Changes Made

  - `libs/aegra-api/src/aegra_api/settings.py`: replace `_SSLMODE_TO_ASYNCPG` dict (mapped to `"true"`/`"false"`) with a `_VALID_SSLMODES` frozenset; pass the original sslmode value through as `ssl=<value>` after lowercasing.
  - `libs/aegra-api/src/aegra_api/settings.py`: update the `verify-ca`/`verify-full` warning — with the corrected translation, asyncpg *does* perform certificate verification against `PGSSLROOTCERT` / `~/.postgresql/root.crt`; the old text claiming "TLS but skip the verify-* 
  check" is no longer accurate.
  - `libs/aegra-api/tests/unit/test_settings.py`: add `test_translated_ssl_value_accepted_by_asyncpg` regression test that actually calls `asyncpg.connect_utils.SSLMode.parse()` on the produced value — closing the gap left by existing tests that only assert string composition.
  - `libs/aegra-api/tests/unit/test_settings.py`: update existing `test_async_url_translates_*` assertions to match the new `ssl=<sslmode>` shape.

  ## Testing

  - [x] Unit tests added/updated
  - [ ] Integration tests added/updated
  - [ ] E2E tests added/updated
  - [x] Manual testing performed

  Manual verification (`asyncpg 0.31.0`, `sqlalchemy 2.0.46`):

  1. **Reproduce on `main`** — `SSLMode.parse("false")` raises `AttributeError` → asyncpg re-raises as `ClientConfigurationError` with the misleading "sslmode parameter must be one of..." message.
  2. **Confirm fix** — translated URL becomes `postgresql+asyncpg://...?ssl=disable`; `SSLMode.parse("disable") == SSLMode.disable` ✓.
  3. **End-to-end against a real Postgres**:
     - `sslmode=disable` against a plain Postgres → connects ✓
     - `sslmode=require` against a Postgres with `ssl=on` + `hostssl`-only `pg_hba.conf` → connects via SSL ✓
     - `sslmode=allow` against the same SSL-required Postgres → asyncpg correctly retries with SSL after non-SSL is rejected (`pg_stat_ssl.ssl = true`) ✓
  4. **Negative case** — unknown sslmode values (`?sslmode=bogus`) still log a warning and drop the param.

  ## Checklist

  - [x] Code follows project style (Ruff formatting) 
  - [x] All linting checks pass (`make lint`)
  - [x] Type checking passes (`make type-check`)
  - [x] All tests pass (`make test`)
  - [x] Documentation updated (if needed) — *N/A: no public docs reference the internal `ssl=true`/`ssl=false` translation; user-facing recommendation (`PGSSLMODE` env var) is unchanged.*
  - [x] Commit messages follow [Conventional Commits](https://www.conventionalcommits.org/)
  - [x] PR title follows Conventional Commits format

  ## Screenshots (if applicable)

  N/A

  ## Additional Notes

  - Root cause is upstream tightening: asyncpg 0.28+ routes string `ssl` kwargs through `SSLMode.parse()` (`connect_utils.py:680-687`), and SQLAlchemy's asyncpg dialect (`create_connect_args`) forwards URL query params verbatim without coercing `ssl` from str to bool. The
  previous test suite only asserted URL string composition — it never instantiated a connection — which is why the bug shipped and CI never flagged it. The new regression test (`test_translated_ssl_value_accepted_by_asyncpg`) calls `SSLMode.parse()` directly to catch this class
   of issue.
  - `database_url_sync` (psycopg / LangGraph checkpointer + store) is unaffected: psycopg speaks libpq natively and accepts `sslmode=` as-is.
  - Ironic side note for future readers: *not* specifying `sslmode` at all also works around the bug — asyncpg's default with no `ssl` kwarg is `SSLMode.disable` (`connect_utils.py:815`), unlike libpq's default `prefer`. So this bug specifically punishes users who explicitly
  set `sslmode=`.

## Summary by CodeRabbit

* **Bug Fixes**
  * Stricter handling of database SSL/TLS modes: unknown modes are warned and omitted; certificate-verification modes emit clearer warnings about expected root CA placement.
  * SSL parameter conversion now preserves the mode value (e.g., ssl=require) in converted async database URLs instead of mapping to boolean.

* **Tests**
  * Updated tests to assert preserved SSL mode in converted URLs and to validate accepted parsed SSL values.

<h3>Greptile Summary</h3>

Fixes a startup crash in `DatabaseSettings` when `DATABASE_URL` contains an `?sslmode=` query param: asyncpg ≥ 0.28 validates string `ssl` kwargs via `SSLMode.parse()`, which rejects `"true"`/`"false"` with `ClientConfigurationError`. The fix replaces the `_SSLMODE_TO_ASYNCPG` dict with a `_VALID_SSLMODES` frozenset and passes the libpq sslmode value through verbatim as `ssl=<value>`.

- **`settings.py`**: `_SSLMODE_TO_ASYNCPG` removed; `sslmode` is now translated inline to `ssl=<normalized-value>` and dropped from `_LIBPQ_ONLY_PARAMS`. The `allow`→`prefer` remapping is also dropped (asyncpg supports `allow` natively). The verify-ca/verify-full warning is updated to reflect that asyncpg will now actually perform cert verification.
- **`test_settings.py`**: Parametrized assertions updated to expect `ssl=<sslmode>` (e.g. `ssl=allow` instead of `ssl=prefer`). A new regression test (`test_translated_ssl_value_accepted_by_asyncpg`) calls `SSLMode.parse()` directly on the emitted value, closing the gap that let the original bug ship undetected.

<h3>Confidence Score: 5/5</h3>

Safe to merge — the core sslmode translation logic is correct, well-tested, and manually verified against a real Postgres instance.

The fix is narrowly scoped to sslmode param translation in a single static method. The new regression test calls SSLMode.parse() directly, closing the validation gap that allowed the original bug to ship. The allow→allow passthrough (dropping the old allow→prefer remap) is validated by the same test. No data path, auth boundary, or migration is touched.

The top-level import of asyncpg.connect_utils.SSLMode in the test file is the only thing worth a second look — see inline comment.

<h3>Important Files Changed</h3>

| Filename | Overview |
|----------|----------|
| libs/aegra-api/src/aegra_api/settings.py | Replaces the _SSLMODE_TO_ASYNCPG dict (which incorrectly mapped allow→prefer and emitted true/false) with a _VALID_SSLMODES frozenset; sslmode values are now passed through verbatim as ssl=<value>. Removes sslmode from _LIBPQ_ONLY_PARAMS (it is handled inline). Warning message for verify-ca/verify-full updated to reflect correct cert-verification behavior. Logic is correct. |
| libs/aegra-api/tests/unit/test_settings.py | Updates translation assertions to match new ssl=<sslmode> shape; adds test_translated_ssl_value_accepted_by_asyncpg that calls SSLMode.parse() directly. Main concern: SSLMode is now imported at module level from a private asyncpg internal, so any future relocation of the symbol would cause all tests in the file to fail at collection time. |

</details>

<h3>Flowchart</h3>

```mermaid
%%{init: {'theme': 'neutral'}}%%
flowchart TD
    A["DATABASE_URL with ?sslmode=X"] --> B["_translate_libpq_params_for_asyncpg()"]
    B --> C{key == 'sslmode'?}
    C -- yes --> D["normalized = value.lower()"]
    D --> E{normalized in _VALID_SSLMODES?}
    E -- no --> F["warn + drop param"]
    E -- yes --> G{normalized in verify-ca / verify-full?}
    G -- yes --> H["emit cert-verification warning"]
    G -- no --> I["append ('ssl', normalized)"]
    H --> I
    C -- no --> J{key in _LIBPQ_ONLY_PARAMS?}
    J -- yes --> K["warn + drop param"]
    J -- no --> L["append (key, value) verbatim"]
    I --> M["async URL: ...?ssl=require"]
    L --> M
```

<a href="https://app.greptile.com/ide/claude-code?prompt=Fix%20the%20following%201%20code%20review%20issue.%20Work%20through%20them%20one%20at%20a%20time%2C%20proposing%20concise%20fixes.%0A%0A---%0A%0A%23%23%23%20Issue%201%20of%201%0Alibs%2Faegra-api%2Ftests%2Funit%2Ftest_settings.py%3A6%0A**Hard%20top-level%20import%20of%20private%20asyncpg%20symbol**%0A%0A%60asyncpg.connect_utils%60%20is%20an%20internal%2C%20undocumented%20module.%20Importing%20%60SSLMode%60%20at%20module%20level%20means%20that%20if%20a%20future%20asyncpg%20release%20moves%20or%20renames%20the%20symbol%2C%20every%20test%20in%20this%20file%20will%20fail%20to%20collect%20%E2%80%94%20not%20just%20the%20SSLMode%20regression%20test.%20The%20previous%20approach%20%28%60pytest.importorskip%60%20%2B%20%60getattr%28...%2C%20None%29%60%29%20degraded%20gracefully%20with%20a%20loud%20skip%3B%20this%20approach%20breaks%20the%20entire%20suite%20silently.%0A%0AConsider%20guarding%20this%20with%20a%20try%2Fexcept%20and%20marking%20the%20test%20class%20with%20a%20module-level%20%60skipif%60%2C%20or%20restoring%20the%20%60importorskip%60%20pattern%20inside%20the%20regression%20test.%20The%20%60%23%20type%3A%20ignore%5Bimport-untyped%5D%60%20already%20signals%20awareness%20that%20this%20is%20a%20private%20import.%0A%0A&repo=aegra%2Faegra&pr=405&platform=github"><picture><source media="(prefers-color-scheme: dark)" srcset="https://greptile-static-assets.s3.amazonaws.com/badges/FixAllInClaudeDark.svg?v=3"><source media="(prefers-color-scheme: light)" srcset="https://greptile-static-assets.s3.amazonaws.com/badges/FixAllInClaude.svg?v=3">Fix All in Claude Code</picture></a> <a href="https://app.greptile.com/api/ide/cursor?prompt=Fix%20the%20following%201%20code%20review%20issue.%20Work%20through%20them%20one%20at%20a%20time%2C%20proposing%20concise%20fixes.%0A%0A---%0A%0A%23%23%23%20Issue%201%20of%201%0Alibs%2Faegra-api%2Ftests%2Funit%2Ftest_settings.py%3A6%0A**Hard%20top-level%20import%20of%20private%20asyncpg%20symbol**%0A%0A%60asyncpg.connect_utils%60%20is%20an%20internal%2C%20undocumented%20module.%20Importing%20%60SSLMode%60%20at%20module%20level%20means%20that%20if%20a%20future%20asyncpg%20release%20moves%20or%20renames%20the%20symbol%2C%20every%20test%20in%20this%20file%20will%20fail%20to%20collect%20%E2%80%94%20not%20just%20the%20SSLMode%20regression%20test.%20The%20previous%20approach%20%28%60pytest.importorskip%60%20%2B%20%60getattr%28...%2C%20None%29%60%29%20degraded%20gracefully%20with%20a%20loud%20skip%3B%20this%20approach%20breaks%20the%20entire%20suite%20silently.%0A%0AConsider%20guarding%20this%20with%20a%20try%2Fexcept%20and%20marking%20the%20test%20class%20with%20a%20module-level%20%60skipif%60%2C%20or%20restoring%20the%20%60importorskip%60%20pattern%20inside%20the%20regression%20test.%20The%20%60%23%20type%3A%20ignore%5Bimport-untyped%5D%60%20already%20signals%20awareness%20that%20this%20is%20a%20private%20import.%0A%0A&pr=405&platform=github"><picture><source media="(prefers-color-scheme: dark)" srcset="https://greptile-static-assets.s3.amazonaws.com/badges/FixAllInCursorDark.svg?v=3"><source media="(prefers-color-scheme: light)" srcset="https://greptile-static-assets.s3.amazonaws.com/badges/FixAllInCursor.svg?v=3">Fix All in Cursor</picture></a> <a href="https://app.greptile.com/api/ide/codex?prompt=IMPORTANT%3A%20Work%20in%20the%20repository%20%22aegra%2Faegra%22%20on%20the%20existing%20branch%20%22fix%2Fsslmode-asyncpg-strict%22.%20Checkout%20that%20branch%20%E2%80%94%20do%20NOT%20create%20a%20new%20branch%20or%20open%20a%20new%20PR.%20Push%20your%20changes%20to%20%22fix%2Fsslmode-asyncpg-strict%22.%0A%0AFix%20the%20following%201%20code%20review%20issue.%20Work%20through%20them%20one%20at%20a%20time%2C%20proposing%20concise%20fixes.%0A%0A---%0A%0A%23%23%23%20Issue%201%20of%201%0Alibs%2Faegra-api%2Ftests%2Funit%2Ftest_settings.py%3A6%0A**Hard%20top-level%20import%20of%20private%20asyncpg%20symbol**%0A%0A%60asyncpg.connect_utils%60%20is%20an%20internal%2C%20undocumented%20module.%20Importing%20%60SSLMode%60%20at%20module%20level%20means%20that%20if%20a%20future%20asyncpg%20release%20moves%20or%20renames%20the%20symbol%2C%20every%20test%20in%20this%20file%20will%20fail%20to%20collect%20%E2%80%94%20not%20just%20the%20SSLMode%20regression%20test.%20The%20previous%20approach%20%28%60pytest.importorskip%60%20%2B%20%60getattr%28...%2C%20None%29%60%29%20degraded%20gracefully%20with%20a%20loud%20skip%3B%20this%20approach%20breaks%20the%20entire%20suite%20silently.%0A%0AConsider%20guarding%20this%20with%20a%20try%2Fexcept%20and%20marking%20the%20test%20class%20with%20a%20module-level%20%60skipif%60%2C%20or%20restoring%20the%20%60importorskip%60%20pattern%20inside%20the%20regression%20test.%20The%20%60%23%20type%3A%20ignore%5Bimport-untyped%5D%60%20already%20signals%20awareness%20that%20this%20is%20a%20private%20import.%0A%0A&repo=aegra%2Faegra&pr=405&platform=github"><picture><source media="(prefers-color-scheme: dark)" srcset="https://greptile-static-assets.s3.amazonaws.com/badges/FixAllInCodexDark.svg?v=3"><source media="(prefers-color-scheme: light)" srcset="https://greptile-static-assets.s3.amazonaws.com/badges/FixAllInCodex.svg?v=3">Fix All in Codex</picture></a>

<sub>Reviews (5): Last reviewed commit: ["Merge branch &#39;main&#39; into fix/sslmode-asy..."](https://github.com/aegra/aegra/commit/c38193576167ab8cad6cdc258f63e6a3bbd4b34b) | [Re-trigger Greptile](https://app.greptile.com/api/retrigger?id=35571077)</sub>

### CODE REVIEW

**Review by Witaly3 — CHANGES_REQUESTED** [review]
@AllenQU-LR Hi. Went through the diff in detail and verified it end-to-end against a live Postgres (spun up `postgres:18`, ran through a real `create_async_engine` + `SELECT 1`). The fix is correct at its core: on `main`, `ssl=false` crashes with `ClientConfigurationError`; with the fix, `ssl=disable` connects, and `allow`/`prefer`/`require`/`verify-*` all behave exactly per libpq semantics. The regression test calls the real `SSLMode.parse()`, so this class of bug can't silently come back. 64 unit tests green, `ruff`/`ty` clean. Nice work nailing the root cause.

  A few points before merge:

  **1. PR description disagrees with the diff on the version bump.** The "Changes Made" section says "Bump version `0.9.18 → 0.9.19` in both pyproject.toml", but there's no bump in the diff — both files are still `0.9.18`. No bump needed here; just drop that line from the description so the diff and the text match.

  **2. Inline imports in the new test violate the project's "imports at top" rule.** In `test_translated_ssl_value_accepted_by_asyncpg`:
  ```python
  from urllib.parse import parse_qs, urlsplit
  from asyncpg.connect_utils import SSLMode  # type: ignore[import-untyped]
  ```
  `urllib.parse` is already imported at the top of the file (`from urllib.parse import quote_plus`), and `asyncpg` is a hard direct dependency (`asyncpg>=0.30.0`), not optional. Neither exception to the rule applies (no proven circular import, not an optional dep). Please move these to the top: `from urllib.parse import parse_qs, quote_plus, urlsplit` and add `from asyncpg.connect_utils import SSLMode` to the top import block.

  **3. The "Testing" checklist is overstated.** "Integration tests added/updated" and "E2E tests added/updated" are checked, but the diff only adds a unit test. For this bug a unit test exercising the real `SSLMode.parse()` is sufficient (the breakage is purely at URL-composition level), so there's no need to add integration/E2E — just uncheck those two boxes so reviewers aren't misled.

  **4. Remove `"sslmode"` from `_LIBPQ_ONLY_PARAMS` — it's now dead code.** Since `sslmode` is handled by the `if key == "sslmode"` branch above, it never reaches the `elif key in _LIBPQ_ONLY_PARAMS` check, so its membership in the frozenset has no effect. Please drop the `"sslmode"` entry so the set only lists params that are actually stripped:
  ```python
  _LIBPQ_ONLY_PARAMS: frozenset[str] = frozenset(
      {
          "sslcert",
          "sslkey",
          "sslrootcert",
          "sslcrl",
          "channel_binding",
          "gssencmode",
          "target_session_attrs",
      }
  )
  ```
  The comment above it stays accurate — these are the libpq-only params that get dropped with a warning.

  Points 1 and 3 are description-only; points 2 and 4 are small code cleanups. The fix itself looks good on the merits.

**Comment by AllenQU-LR** [comment]
Thank you for your review. It seems that others have already fixed the bug in this PR: https://github.com/aegra/aegra/pull/409, so I will close this PR.
